### ISSUE TITLE
为什么生成的图片质量和论文里的差那么多？

### ISSUE THREAD

**Issue by AlexRenl** [wuleiaty/DocUNet#2]

**Comment by wuleiaty** [comment]
生成图片的质量与设置的图片尺寸有关系，生成图片的尺寸可在_data/config.json_文件里设置。其中有两个尺寸选项可以设置。第一个是变形前的缩放尺寸，作用是用来在变形运算前压缩原图质量以加快运算速度。第二个是变形后的缩放尺寸，也就是最后输出的尺寸，这个作用是用来统一所有数据的尺寸以便用来训练。建议输出尺寸为352*272，变形前尺寸不小于输出尺寸。使用原图尺寸进行训练会非常耗时并且占显存，实际上论文作者也是使用小尺寸图片进行训练，在预测阶段可以使用尺寸大一些的数据
