### ISSUE TITLE
Where to download scanned images and texture image?

### ISSUE THREAD

**Issue by xuewenyuan** [wuleiaty/DocUNet#4]
Thank you for your contribution! It is important for this paper that proposes a method to generate deformable data. However, where I can download the scanned images and texture image? So, I can run the code to generate deformable data.

**Comment by Sqrt5** [comment]
> Thank you for your contribution! It is important for this paper that proposes a method to generate deformable data. However, where I can download the scanned images and texture image? So, I can run the code to generate deformable data.

https://www.robots.ox.ac.uk/~vgg/data/dtd/

**Comment by xuewenyuan** [comment]
@Sqrt5 Thank you!

**Comment by chengmengli06** [comment]
> > Thank you for your contribution! It is important for this paper that proposes a method to generate deformable data. However, where I can download the scanned images and texture image? So, I can run the code to generate deformable data.
> 
> https://www.robots.ox.ac.uk/~vgg/data/dtd/

dtd are the texture images, where to download the scanned images?

**Comment by gaoshangle** [comment]
> 
where to download the scanned images?
Thank you!
